# Version
version: "3.8"

# Servicios
services:
  # Base de datos 
  graphql_crud:
    # Imagen y nombre del contenedor
    image: postgres:13
    container_name: graphql_crud
    # Cargamos las variables de entorno
    env_file: ./.env
    # Credenciales
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
    # Puerto en el que nos conectaremos : Puerto exterior 
      - $DB_PORT:$DB_DOCKER_PORT
    volumes:
      - graphql-crud-db-data:/var/lib/postgresql/data/pgdata

# Volumenes de guardado de informacion
volumes:
  graphql-crud-db-data: